package myteam;

import myteam.Person;

rule "John rule"
no-loop
    when
        $p : Person(name == "john")
    then
        modify ($p){
            setAge(35)
        }
        System.out.println("Hello " + $p.getName());

end

rule "Mary rule"
no-loop
    when
        $p : Person(name == "mary")
    then
        modify ($p){
            setAge(18)
        }
        System.out.println("Hello " + $p.getName());

end

rule "Pavan rule"
no-loop
    when
        $p : Person(name == "pavan")
    then
        modify ($p){
            setAge(30)
        }
        System.out.println("Hello " + $p.getName());

end

rule "XYZ rule"
no-loop
    when
        $p : Person(name == "XYZ")
    then
        modify ($p){
            setAge(30)
        }
        System.out.println("Hello " + $p.getName());

end

rule "Phani rule"
no-loop
    when
        $p : Person(name == "Phani")
    then
        modify ($p){
            setAge(32)
        }
        System.out.println("Hello " + $p.getName());

end
